create database colonie;

\c colonie

drop table if exists actions cascade;
drop table if exists scenarios cascade;
drop table if exists humains cascade;
drop table if exists robots cascade;

create table robots (
    id_robot integer generated by default as identity primary key,
    nom_robot text not null unique,
    modele text not null,
    etat text not null check(etat in ('actif','hors_service','en_panne'))
);

create table humains (
    id_humain integer generated by default as identity primary key,
    nom text not null,
    vulnerabilite text not null check(vulnerabilite in ('élevée','moyenne','faible')),
    localisation text
);

create table scenarios (
    id_scenario integer generated by default as identity primary key,
    description text not null,
    priorite_loi integer not null check(priorite_loi in (1,2,3))
);

create table actions (
    id_action integer generated by default as identity primary key,
    id_robot integer references robots(id_robot) on delete set null,
    id_humain integer references humains(id_humain) on delete set null,
    id_scenario integer references scenarios(id_scenario) on delete set null,
    action text not null,
    timestamp timestamp not null,
    resultat text not null check(resultat in ('succès','échec','mitigé'))
);

create index idx_actions_robot on actions(id_robot);
create index idx_actions_scenario on actions(id_scenario);
create index idx_scenarios_priorite on scenarios(priorite_loi);
create index idx_robots_etat on robots(etat);
