-- Schéma et données de test pour la colonie (SQLite-compatible)
-- Tables: robots, humains, scenarios, actions

-- PostgreSQL schema et nettoyage

-- Creation database
CREATE DATABASE colonie;

-- Connexion à la base de données colonie
\c colonie;

-- Supprimer les tables dans le bon ordre si elles existent
DROP TABLE IF EXISTS actions CASCADE;
DROP TABLE IF EXISTS scenarios CASCADE;
DROP TABLE IF EXISTS humains CASCADE;
DROP TABLE IF EXISTS robots CASCADE;

-- Table robots
CREATE TABLE robots (
    id_robot INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_robot TEXT NOT NULL UNIQUE,
    modele TEXT NOT NULL,
    etat TEXT NOT NULL CHECK(etat IN ('actif','hors_service','en_panne'))
);

-- Table humains
CREATE TABLE humains (
    id_humain INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    vulnerabilite TEXT NOT NULL CHECK(vulnerabilite IN ('élevée','moyenne','faible')),
    localisation TEXT
);

-- Table scenarios
CREATE TABLE scenarios (
    id_scenario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    priorite_loi INTEGER NOT NULL CHECK(priorite_loi IN (1,2,3))
);

-- Table actions
-- Les colonnes de FK doivent être NULLABLE si on veut utiliser ON DELETE SET NULL
CREATE TABLE actions (
    id_action INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_robot INTEGER REFERENCES robots(id_robot) ON DELETE SET NULL,
    id_humain INTEGER REFERENCES humains(id_humain) ON DELETE SET NULL,
    id_scenario INTEGER REFERENCES scenarios(id_scenario) ON DELETE SET NULL,
    action TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    resultat TEXT NOT NULL CHECK(resultat IN ('succès','échec','mitigé'))
);

-- Création des index pour optimisation des requêtes (Partie I - Étape 1)
CREATE INDEX idx_actions_robot ON actions(id_robot);
CREATE INDEX idx_actions_scenario ON actions(id_scenario);
CREATE INDEX idx_scenarios_priorite ON scenarios(priorite_loi);
CREATE INDEX idx_robots_etat ON robots(etat);
